const { default: Home } = require("./screens/Home");

module.exports = {
  readme:
    "socialss naming need to change, socials is actual the id of all socialss",
  socials_list: [
    "facebook",
    "whatsapp",
    "telegram",
    "linkedin",
    "line",
    "skype",
    "twitter",
    "wechat",
    "instagram",
    "foursquare",
    "xiaohongshu",
    "reddit",
  ],
  state_false: {
    name: false,
    notes: false,
    nickname: false,
    title: false,
    role: false,
    organization: false,
    workemail: false,
    phone: false,
    homephone: false,
    workphone: false,
    homefax: false,
    workfax: false,
    url: false,
    workurl: false,
    birthday: false,
    address: false,
    workaddress: false,
    facebook: false,
    whatsapp: false,
    telegram: false,
    linkedin: false,
    line: false,
    skype: false,
    twitter: false,
    wechat: false,
    instagram: false,
    foursquare: false,
    xiaohongshu: false,
    reddit: false,
  },
  state_true: {
    name: true,
    notes: true,
    nickname: true,
    title: true,
    role: true,
    organization: true,
    workemail: true,
    phone: true,
    homephone: true,
    workphone: true,
    homefax: true,
    workfax: true,
    url: true,
    workurl: true,
    birthday: true,
    address: true,
    workaddress: true,
    facebook: true,
    whatsapp: true,
    telegram: true,
    linkedin: true,
    line: true,
    skype: true,
    twitter: true,
    wechat: true,
    instagram: true,
    foursquare: true,
    xiaohongshu: true,
    reddit: true,
  },
  messaging: ["whatsapp", "wechat", "line", "telegram"],
  patterns:{
    regex : /.*\/([^/?]+)\/?.*$/,
    /* regex1 : /^https:\/\/www\.foodpanda\.(my|sg)\//, */
    regex1 : /www\.foodpanda\.my\/(.*)/,

  },
  socials: [
    {
      id: "facebook",
      value: "facebook",
      label: "Facebook",
      title: "Facebook",
      src: "../images/facebook.png",
      isUrl: true,
      example: "www.facebook.com/itap.3",
      pattern: /facebook.com\/(.*)/,
      link: "https://www.facebook.com/",
      shortlink: "www.facebook.com/",
      vcard: "Facebook",
    },
    {
      id: "whatsapp",
      value: "whatsapp",
      label: "Whatsapp",
      title: "Whatsapp Messenger",
      src: "../images/whatsapp.png",
      isUrl: true,
      example: "https://wa.me/601112345678",
      pattern: /https:\/\/(?:wa\.me\/|api\.whatsapp\.com\/send\?phone=)(.*)/,
      /* link: "https://api.whatsapp.com/send?phone=", */
      link: "https://wa.me/",
      shortlink: "wa.me/",
      vcard: "WhatsappMessenger",
    },
    {
      id: "instagram",
      value: "instagram",
      label: "Instagram",
      title: "Instagram",
      src: "../images/instagram.png",
      isUrl: true,
      example: "https://www.instagram.com/vipbakeryshop/",
      pattern: /instagram\.com\/([^?]+)/,
      link: "https://www.instagram.com/",
      shortlink: "www.instagram.com/",
      vcard: "Instagram",
    },
    {
      id: "twitter",
      value: "twitter",
      label: "Twitter",
      title: "Twitter",
      src: "../images/twitter.png",
      isUrl: true,
      example: "https://www.twitter.com/@loh_meng",
      pattern: /twitter.com\/(.*)/,
      link: "https://www.twitter.com/",
      shortlink: "www.twitter.com/",
      vcard: "Twitter",
    },
    {
      id: "telegram",
      value: "telegram",
      label: "Telegram",
      title: "Telegram Messenger",
      src: "../images/telegram.png",
      isUrl: true,
      example: "https://t.me/Oriorz",
      pattern: /t.me\/(.*)/,
      link: "https://t.me/",
      shortlink: "t.me/",
      vcard: "TelegramMessenger",
    },
    {
      id: "linkedin",
      value: "linkedin",
      label: "Linkedin",
      title: "Linkedin",
      src: "../images/linkedin.png",
      isUrl: true,
      example: "https://www.linkedin.com/in/mark-zuckerberg-618bba58/",
      pattern: /linkedin.com\/in\/(.*)/,
      link: "https://www.linkedin.com/in/",
      shortlink: "www.linkedin.com/in/",
      vcard: "Linkedin",
    },
    {
      id: "linkedincompany",
      value: "linkedincompany",
      label: "Linkedin Company",
      title: "Linkedin Company",
      src: "../images/linkedin.png",
      isUrl: true,
      example: "https://www.linkedin.com/company/spa8/",
      pattern: /linkedin.com\/company\/(.*)/,
      link: "https://www.linkedin.com/company/",
      shortlink: "www.linkedin.com/company/",
      vcard: "Linkedin",
    },
    {
      id: "line",
      value: "line",
      label: "Line",
      title: "Line",
      src: "../images/line.png",
      isUrl: true,
      example: "https://line.me/ti/p/@linedevelopers",
      pattern: /ti\/p\/(.*)/,
      link: "https://line.me/ti/p/",
      shortlink: "line.me/ti/p/",
      vcard: "Line",
    },
    /* {
      id: "skype",
      value: "skype",
      label: "Skype",
      title: "Skype",
      src: "../images/skype.png",
      isUrl: true,
      example: "...",
      pattern: /www.facebook.com\/(.*)/,
      link: "https://www.skype.com/",
      shortlink: "www.skype.com/",
      vcard: "Skype",
    }, */
    {
      id: "wechat",
      value: "wechat",
      label: "Wechat",
      title: "Wechat",
      src: "../images/wechat.png",
      isUrl: false,
      example: "yangmimini",
      pattern: /(.*)/,
      link: "",
      shortlink: "",
      vcard: "Wechat",
    },
    {
      id: "foursquare",
      value: "foursquare",
      label: "Foursquare",
      title: "Foursquare",
      src: "../images/foursquare.png",
      isUrl: true,
      example: "https://foursquare.com/v/vertigo/5b2ceb9dd69ed00039bdbae0",
      pattern: /foursquare.com\/v\/(.*)/,
      link: "https://foursquare.com/",
      shortlink: "foursquare.com/",
      vcard: "Foursquare",
    },
    {
      id: "xiaohongshu",
      value: "xiaohongshu",
      label: "Xiaohongshu",
      title: "小红书",
      src: "../images/xiaohongshu.png",
      isUrl: true,
      example: "https://www.xiaohongshu.com/user/profile/60ccb6c000000000010015ef",
      pattern: /xiaohongshu.com\/user\/profile\/(.*)/,
      link: "https://www.xiaohongshu.com/user/profile/",
      shortlink: "https://www.xiaohongshu.com/user/profile/",
      vcard: "xiaohongshu",
    },
    {
      id: "reddit",
      value: "reddit",
      label: "Reddit",
      title: "Reddit",
      src: "../images/reddit.png",
      isUrl: true,
      example: "https://www.reddit.com/user/mohalnahhas/",
      pattern: /reddit.com\/user\/(.*)/,
      link: "https://www.reddit.com/user/",
      shortlink: "www.reddit.com/user/",
      vcard: "Reddit",
    },
    {
      id: "tiktok",
      value: "tiktok",
      label: "Tiktok",
      title: "Tiktok",
      src: "../images/tiktok.svg",
      isUrl: true,
      example: "https://www.tiktok.com/@justinflom",
      pattern: /tiktok.com\/(.*)/,
      link: "https://www.tiktok.com/",
      shortlink: "www.tiktok.com/",
      vcard: "Tiktok",
    },
    {
      id: "9gag",
      value: "9gag",
      label: "9gag",
      title: "9gag",
      src: "../images/9gag.png",
      isUrl: true,
      example: "https://9gag.com/u/nonsense91",
      pattern: /9gag.com\/u\/(.*)/,
      link: "https://9gag.com/u/",
      shortlink: "9gag.com/u/",
      vcard: "9gag",
    },
    {
      id: "patreon",
      value: "patreon",
      label: "Patreon",
      title: "Patreon",
      src: "../images/patreon.png",
      isUrl: true,
      example: "https://www.patreon.com/Kurzgesagt",
      pattern: /patreon.com\/(.*)/,
      link: "https://www.patreon.com/",
      shortlink: "www.patreon.com/",
      vcard: "Patreon",
    },
    {
      id: "twitch",
      value: "twitch",
      label: "Twitch",
      title: "Twitch",
      src: "../images/twitch.png",
      isUrl: true,
      example: "https://www.twitch.tv/saiiren",
      pattern: /twitch.tv\/(.*)/,
      link: "https://www.twitch.tv/",
      shortlink: "www.twitch.tv/",
      vcard: "Twitch",
    },
    {
      id: "weibo",
      value: "weibo",
      label: "Weibo",
      title: "Weibo",
      src: "../images/weibo.png",
      isUrl: true,
      example: "https://m.weibo.cn/u/1815418641",
      pattern: /weibo.cn\/u\/(.*)/,
      link: "https://m.weibo.cn/u/",
      shortlink: "m.weibo.cn/u/",
      vcard: "Weibo",
    },
    {
      id: "medium",
      value: "medium",
      label: "Medium",
      title: "Medium",
      src: "../images/medium.png",
      isUrl: true,
      example: "https://medium.com/@michael_at_message",
      pattern: /medium.com\/(.*)/,
      link: "https://medium.com/",
      shortlink: "medium.com/",
      vcard: "Medium",
    },
    {
      id: "tumblr",
      value: "tumblr",
      label: "Tumblr",
      title: "Tumblr",
      src: "../images/tumblr.png",
      isUrl: true,
      example: "https://www.tumblr.com/vulcanette",
      pattern: /tumblr.com\/(.*)/,
      link: "https://tumblr.com/",
      shortlink: "tumblr.com/",
      vcard: "Tumblr",
    },
    {
      id: "youtube",
      value: "youtube",
      label: "Youtube",
      title: "Youtube",
      src: "../images/youtube.png",
      isUrl: true,
      example: "https://www.youtube.com/@MrBeast/",
      pattern: /youtube.com\/(.*)/,
      link: "https://youtube.com/",
      shortlink: "youtube.com/",
      vcard: "Youtube",
    },
    {
      id: "threads",
      value: "threads",
      label: "Threads",
      title: "Threads",
      src: "../images/threads.png",
      isUrl: true,
      example: "https://www.threads.net/@lowcostcosplayth",
      pattern: /threads.net\/(.*)/,
      link: "https://threads.net/",
      shortlink: "threads.net/",
      vcard: "Threads",
    },
  ],
  bios: [
    {
      id: "name",
      title: "Name",
      src: "../images/name.jpg",
      example: "...",
      vcard: "Name",
    },
    {
      id: "nickname",
      title: "NickName (Optional)",
      src: "../images/name.jpg",
      example: "...",
      vcard: "NickName",
    },
    {
      id: "workemail",
      title: "Work Email (Optional)",
      src: "../images/email.png",
      example: "...",
      vcard: "work-email",
    },
    {
      id: "title",
      title: "Title (Optional)",
      src: "../images/title.jpg",
      example: "...",
      vcard: "Title",
    },
    /* {
      id: "role",
      title: "Role (Optional)",
      src: "../images/title.jpg",
      example: "...",
      vcard: "Role"
    }, */
    {
      id: "organization",
      title: "Organization (Optional)",
      src: "../images/title.jpg",
      example: "...",
      vcard: "Organization",
    },
    {
      id: "phone",
      title: "Handphone",
      src: "../images/phone.png",
      example: "...",
      vcard: "phone",
    },
    {
      id: "homephone",
      title: "Home Phone (Optional)",
      src: "../images/phone.png",
      example: "...",
      vcard: "home",
    },
    {
      id: "workphone",
      title: "Work Phone (Optional)",
      src: "../images/phone.png",
      example: "...",
      vcard: "Work",
    },
    {
      id: "homefax",
      title: "Home Fax (Optional)",
      src: "../images/fax.jpg",
      example: "...",
      vcard: "homefax",
    },
    {
      id: "workfax",
      title: "Work Fax (Optional)",
      src: "../images/fax.jpg",
      example: "...",
      vcard: "workfax",
    },
    {
      id: "url",
      title: "Personal Website",
      src: "../images/website.jpg",
      example: "...",
      vcard: "url",
    },
    {
      id: "workurl",
      title: "Office Website",
      src: "../images/website.jpg",
      example: "...",
      vcard: "workurl",
    },
    {
      id: "birthday",
      title: "Birthday (optional)",
      src: "../images/birthday.jpg",
      example: "...",
      vcard: "birthday",
    },
    {
      id: "address",
      title: "Address (optional)",
      src: "../images/address.jpg",
      example: "...",
      vcard: "address",
    },
    {
      id: "workaddress",
      title: "Work Address (optional)",
      src: "../images/address.jpg",
      example: "...",
      vcard: "workaddress",
    },
  ],
  sales: [
    {
      id: "grabfood",
      value: "grabfood",
      label: "Grab Food",
      title: "Grab Food",
      src: "../images/grab.png",
      isUrl: true,
      example: "https://food.grab.com/my/en/restaurant/gindaco-pavilion-elite-delivery/1-CYVKVKJZJNCKT2",
      pattern: /food.grab.com\/my\/(.*)/,
      link: "https://food.grab.com/my/",
      shortlink: "www.grab.com/my/",
      vcard: "Grab",
    },
    {
      id: "foodpanda",
      value: "foodpanda",
      label: "Foodpanda",
      title: "Foodpanda",
      src: "../images/foodpanda.png",
      isUrl: true,
      example: "https://www.foodpanda.my/restaurant/o4dw/bob-burger-batu-13",
      pattern: /foodpanda.my\/(.*)/,
      link: "https://www.foodpanda.my/",
      shortlink: "www.foodpanda.my/",
      vcard: "Foodpanda",
    },
    {
      id: "99.co",
      value: "99.co",
      label: "99.co",
      title: "99.co",
      src: "../images/99.co.png",
      isUrl: true,
      example: "https://www.99.co/singapore/agents/R059742F-jackson-b.",
      pattern: /99.co\/singapore\/agents\/(.*)/,
      link: "https://www.99.co/singapore/agents/",
      shortlink: "www.99.co/singapore/agents/",
      vcard: "99.co",
    },
    {
      id: "99.co_listing",
      value: "99.co listing",
      label: "99.co Listing",
      title: "99.co Listing",
      src: "../images/99co.png",
      isUrl: true,
      example: "https://www.99.co/singapore/rent/property/103-bedok-reservoir-road-hdb-8HhnjwiddiMU5ohnaoAwtL",
      pattern: /99.co\/singapore\/(.*)/,
      link: "https://www.99.co/singapore/",
      shortlink: "www.99.co/singapore/",
      vcard: "99.co_listing",
    },
    {
      id: "agoda",
      value: "agoda",
      label: "Agoda",
      title: "Agoda",
      src: "../images/agoda.png",
      isUrl: true,
      example: "https://www.agoda.com/minsu-ekocheras-h10235854/hotel/kuala-lumpur-my.html",
      pattern: /agoda.com\/(.*)/,
      link: "https://www.agoda.com/",
      shortlink: "www.agoda.com/",
      vcard: "agoda",
    },
    {
      id: "airbnb",
      value: "airbnb",
      label: "Airbnb",
      title: "Airbnb",
      src: "../images/airbnb.png",
      isUrl: true,
      example: "https://www.airbnb.com/users/show/15876345",
      pattern: /airbnb.com\/users\/show\/(.*)/,
      link: "https://www.airbnb.com/users/show/",
      shortlink: "www.airbnb.com/users/show/",
      vcard: "airbnb",
    },
    {
      id: "booking",
      value: "booking",
      label: "Booking",
      title: "Booking",
      src: "../images/booking.png",
      isUrl: true,
      example: "https://www.booking.com/hotel/my/lucantia-serviced-suites-kuala-lumpur.html?aid=304142",
      pattern: /booking.com\/hotel\/my\/(.*)/,
      link: "https://www.booking.com/hotel/my/",
      shortlink: "www.booking.com/hotel/my/",
      vcard: "booking",
    },
    {
      id: "propertyguru_my",
      value: "propertyguru_my",
      label: "Propertyguru_my",
      title: "Propertyguru_my",
      src: "../images/propertyguru.png",
      isUrl: true,
      example: "https://www.propertyguru.com.my/property-agents/jimmy-tan-15296625#Agent-RightSideProfile",
      pattern: /propertyguru.com.my\/property-agents\/(.*)/,
      link: "https://www.propertyguru.com.my/property-agents/",
      shortlink: "www.propertyguru.com.my/property-agents/",
      vcard: "propertyguru_my",
    },
    /* "lazada",
    "shopee",
    "taobao",
    "carousell",
    "propertyguru",
    "iproperty", */
  ],
  games: ["pokemon", "lol", "mlbb", "nintendoswitch", "steam"],
  ewallet: ["tng", "grab", "boost", "maybank2u", "bankacc"],
};
